
export const Icons = {
        '01d' : require(`../images/01d.png`),
        '02d' : require(`../images/02d.png`),
        '03d' : require(`../images/03d.png`),
        '04d' : require(`../images/04d.png`),
        '09d' : require(`../images/09d.png`),
        '10d' : require(`../images/10d.png`),
        '11d' : require(`../images/11d.png`),
        '13d' : require(`../images/13d.png`),
        '50d' : require(`../images/50d.png`),
        '01n' : require(`../images/01n.png`),
        '02n' : require(`../images/02n.png`),
        '03n' : require(`../images/03n.png`),
        '04n' : require(`../images/04n.png`),
        '09n' : require(`../images/09n.png`),
        '10n' : require(`../images/10n.png`),
        '11n' : require(`../images/11n.png`),
        '13n' : require(`../images/13n.png`),
        '50n' : require(`../images/50n.png`),
};